# Generated by Django 2.2.6 on 2020-05-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C21Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_name', models.CharField(max_length=10)),
                ('salary', models.FloatField(default=None)),
                ('graduation_school', models.CharField(default='湖南理工学院', max_length=50)),
                ('age', models.IntegerField(default=24)),
                ('sex', models.CharField(default='女', max_length=4)),
                ('company', models.CharField(default='阿里巴巴', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=4)),
                ('event_limit', models.IntegerField()),
                ('event_status', models.IntegerField()),
                ('event_address', models.CharField(max_length=4)),
                ('event_start_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField(default=30)),
                ('email', models.EmailField(default=None, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(default='女', max_length=2)),
            ],
        ),
    ]
