# Generated by Django 2.2.6 on 2019-10-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField(default=None)),
                ('email', models.EmailField(default=None, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(default='女', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='c21_students',
            name='age',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='c21_students',
            name='company',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='c21_students',
            name='graduation_school',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='c21_students',
            name='salary',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='c21_students',
            name='sex',
            field=models.CharField(default='女', max_length=4),
        ),
    ]
