# Generated by Django 2.2.6 on 2019-10-09 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20191009_1514'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='C21_students',
            new_name='C21Students',
        ),
    ]
