# Generated by Django 2.2.6 on 2019-10-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_auto_20191009_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c21students',
            name='company',
            field=models.CharField(default='阿里巴巴', max_length=40),
        ),
        migrations.AlterField(
            model_name='c21students',
            name='graduation_school',
            field=models.CharField(default='湖南理工学院', max_length=50),
        ),
        migrations.AlterField(
            model_name='groupinformation',
            name='age',
            field=models.IntegerField(default=30),
        ),
    ]
