# Generated by Django 2.2.12 on 2020-04-09 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_auto_20200314_2330'),
        ('TestModel', '0004_auto_20191012_1133'),
    ]

    operations = [
    ]
